spring.application.name=iatracker-backend
server.port=9090

# MySQL - Aiven Cloud Database
spring.datasource.url=jdbc:mysql://ia-tracker-db-suryaprakash-c8e3.j.aivencloud.com:26966/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Logging
logging.level.com.iatracker=DEBUG
spring.main.allow-circular-references=true